version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  disable-all: true
  enable:
    - gocyclo
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - funlen
  disable:
    - errcheck

  settings:
    funlen:
      lines: 500
      statements: 250
    gocyclo:
      min-complexity: 80
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

