run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - funlen

linters-settings:
  funlen:
    lines: 500
    statements: 250
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
      - name: package-comments
        disabled: false
