#!/usr/bin/env bash
# Run Go E2E tests with the macOS vm driver.
# All configuration is read from environment variables set by the CI job.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT/packages/nexus"

export NEXUS_VM_ROOTFS="${NEXUS_VM_ROOTFS:-$HOME/.cache/nexus/vm/rootfs.ext4}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# NEXUS_E2E_MACOS_PACKAGES may be set by the CI matrix to run only a subset
# of packages. Defaults to all packages when unset.
if [[ -n "${NEXUS_E2E_MACOS_PACKAGES:-}" ]]; then
  read -ra PACKAGES <<< "$NEXUS_E2E_MACOS_PACKAGES"
else
  PACKAGES=(
    ./test/e2e/harness/...
    ./test/e2e/daemon/...
    ./test/e2e/auth/...
    ./test/e2e/fs/...
    ./test/e2e/project/...
    ./test/e2e/vmproof/...
    ./test/e2e/workspace/...
    ./test/e2e/cli/...
    ./test/e2e/pty/...
    ./test/e2e/spotlight/...
  )
fi

go test -tags e2e -count=1 -timeout=25m -v -p=2 -parallel=2 \
  "${PACKAGES[@]}"
