name: Trigger - Test CD

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - test-cd

permissions:
  contents: write

jobs:
  cd:
    uses: ./.github/workflows/job-cd.yaml
