name: Trigger - Push to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  cd:
    uses: ./.github/workflows/job-cd.yaml
